baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Åskar.se'
theme = 'ananke'



[menu]

  [[menu.main]]
    identifier = "me"
    name = "Me"
    url = "/me"
    weight = 1


  [[menu.main]]
    identifier = "art"
    name = "Art"
    url = "/art"
    weight = 2
